// <auto-generated />
using AspnetCoreEFCoreExample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AspnetCoreEFCoreExample.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20190531083032_EntityBcdRelations")]
    partial class EntityBcdRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspnetCoreEFCoreExample.Models.EntityBee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("EntityBees");
                });

            modelBuilder.Entity("AspnetCoreEFCoreExample.Models.EntityCee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EntityBeeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("EntityBeeId");

                    b.ToTable("EntityCees");
                });

            modelBuilder.Entity("AspnetCoreEFCoreExample.Models.EntityDee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EntityBeeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("EntityBeeId");

                    b.ToTable("EntityDees");
                });

            modelBuilder.Entity("AspnetCoreEFCoreExample.Models.MyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MyModels");
                });

            modelBuilder.Entity("AspnetCoreEFCoreExample.Models.EntityCee", b =>
                {
                    b.HasOne("AspnetCoreEFCoreExample.Models.EntityBee")
                        .WithMany("EntityCees")
                        .HasForeignKey("EntityBeeId");
                });

            modelBuilder.Entity("AspnetCoreEFCoreExample.Models.EntityDee", b =>
                {
                    b.HasOne("AspnetCoreEFCoreExample.Models.EntityBee")
                        .WithMany("EntityDees")
                        .HasForeignKey("EntityBeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
